name: visitor_management_system
description: A visitor management system with Firebase integration

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase Core (required)
  firebase_core: ^2.18.0

  # Syncfusion (charts/date picker)
  syncfusion_flutter_charts: ^30.2.4
  syncfusion_flutter_datepicker: ^30.2.4

  # Firebase Authentication
  firebase_auth: ^4.11.1

  # Cloud Firestore
  cloud_firestore: ^4.9.1

  # Firebase Storage
  firebase_storage: ^11.5.0

  # Firebase Messaging (for push notifications)
  firebase_messaging: ^14.7.1

  # Image Picker (for capturing visitor ID photos)
  image_picker: ^1.0.4

  # Date/Time Formatting
  intl: ^0.18.1

  # UI Components
  fluttertoast: ^8.2.12
  provider: ^6.1.1
  qr_flutter: ^4.1.0
  mobile_scanner: ^6.0.2
  csv: ^6.0.0
  share_plus: ^10.0.2
  path_provider: ^2.1.4
  pdf: ^3.11.0
  printing: ^5.13.4

  # Form Validation
  form_validator: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
